spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB    # Adjust as needed
      max-request-size: 100MB # Adjust as needed
  application:
    name: next-crowd-back-end
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/master.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,configprops,env,metrics
security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    expiration-time: 86400000
  allowedOrigins: ${SECURITY_ALLOWED_ORIGINS}

storage:
  directory: ${STORAGE_DIRECTORY}
  baseUrl: ${STORAGE_BASEURL}

logging:
  level:
    org:
      springframework:
        web: DEBUG
strapi:
  baseUrl: ${STRAPI_BASEURL}
  token: ${STRAPI_TOKEN}