spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB    # Adjust as needed
      max-request-size: 100MB # Adjust as needed
  application:
    name: next-crowd-back-end
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/master.xml
security:
  jwt:
    secret-key: Mzg4NTUwMGEzN2ExZmFjYTMzNmY5MzNjZTYxNzY5NTIwNjBhYTg1OTM5ODA4YzEwMWJiZjk1MTA0OTIxMzVmYjhkMzZiZjFhNmY1NjgyYmQ3MTZiNDNkY2M4YWIyNDRhNTUwNzJiYTEzNzY0NDE4YWJhMzg1YTNkYTJjMDJiZGQ=
    expiration-time: 86400000

storage:
  directory: /tmp/.next-crowd-files/
  baseUrl: http://localhost:8080/public


logging:
  level:
    org:
      springframework:
        web: DEBUG