spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB    # Adjust as needed
      max-request-size: 100MB # Adjust as needed
  application:
    name: next-crowd-back-end
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/nextcrowd_db
    username: nextcrowd_root
    password: nextcrowd_pwd
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/master.xml
security:
  jwt:
    secret-key: Mzg4NTUwMGEzN2ExZmFjYTMzNmY5MzNjZTYxNzY5NTIwNjBhYTg1OTM5ODA4YzEwMWJiZjk1MTA0OTIxMzVmYjhkMzZiZjFhNmY1NjgyYmQ3MTZiNDNkY2M4YWIyNDRhNTUwNzJiYTEzNzY0NDE4YWJhMzg1YTNkYTJjMDJiZGQ=
    expiration-time: 86400000
  allowedOrigins: http://localhost:3000

storage:
  directory: /tmp/.next-crowd-files/
  baseUrl: http://localhost:8001

logging:
  level:
    org:
      springframework:
        web: DEBUG
strapi:
  baseUrl: http://localhost:1337
  token: 05fa3264c489615e205456bebd34da9ad8d5ceea1662c51527de748ac506053443474b2c3eafbcfb4204b218d4a2b1a3cca36514a2f1a4b195202436e52602d5e7f70faa680943be88264d3348577fe3f773a7fb417d65a810ee0aadb7bf3f2252c67c63b3cc599a80ff29c2dbede39ef6bd83c073a6c39a3c1b5d363d83c145
  publicUrl: http://localhost:1337