spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB    # Adjust as needed
      max-request-size: 100MB # Adjust as needed
  application:
    name: next-crowd-back-end
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/nextcrowd_db
    username: nextcrowd_root
    password: nextcrowd_pwd
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/master.xml
security:
  jwt:
    secret-key: Mzg4NTUwMGEzN2ExZmFjYTMzNmY5MzNjZTYxNzY5NTIwNjBhYTg1OTM5ODA4YzEwMWJiZjk1MTA0OTIxMzVmYjhkMzZiZjFhNmY1NjgyYmQ3MTZiNDNkY2M4YWIyNDRhNTUwNzJiYTEzNzY0NDE4YWJhMzg1YTNkYTJjMDJiZGQ=
    expiration-time: 86400000
  allowedOrigins: http://localhost:3000

storage:
  directory: /tmp/.next-crowd-files/
  baseUrl: http://localhost:8001/public/

logging:
  level:
    org:
      springframework:
        web: DEBUG
strapi:
  baseUrl: http://localhost:1337
  token: 8877ac54d0dec222049abf94da4befa55c058b0ab3dddba299f9b74d1a0f8d9e51a636791d4e0787bbdb8ef38d94d5c773ad0d7ffcc48b51e98732ddb4a4fe5de36afd6953fa07a42c3091f2b1892c5cc917973ac1964e073a7339ce80e0bff9f6a2f518a6f8c523176d6be0030e603c4db13aeb0ae78c54867e51666a8ce09d
  publicUrl: http://localhost:1337
