openapi: 3.0.3
info:
  title: Crowdfunding Project Owner API
  description: API for project owners to manage their crowdfunding projects
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

security:
  - BearerAuth: []

paths:
  /projectOwner/projects:
    get:
      summary: Get Pending Review Projects
      description: Retrieve a list of projects pending review owned by the authenticated user.
      parameters:
        - in: query
          name: cursor
          schema:
            type: string
          description: Cursor for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items to return
      responses:
        '200':
          description: List of projects pending review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProjectsResponse'
    post:
      summary: Submit a new crowdfunding project
      description: Allows project owners to submit a new crowdfunding project.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitCrowdfundingProjectCommand'
      responses:
        '200':
          description: Project submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectCreated'
        '400':
          description: Invalid input

  /projectOwner/projects/{projectId}:
    get:
      summary: Get Project by ID
      description: Retrieve details of a specific project owned by the authenticated user.
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
          description: ID of the project
      responses:
        '200':
          description: Project retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrowdfundingProject'
        '404':
          description: Project not found or not owned by the user

  /projectOwner/projects/{projectId}/edit:
    put:
      summary: Edit a crowdfunding project
      description: Allows project owners to update the details of their project.
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
          description: ID of the project to edit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditCrowdfundingProjectCommand'
      responses:
        '200':
          description: Project edited successfully
        '400':
          description: Invalid input or invalid project status
        '404':
          description: Project not found or not owned by the user

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CrowdfundingProject:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        status:
          type: string
        owner:
          $ref: '#/components/schemas/ProjectOwner'
        requestedAmount:
          type: number
          format: double
        collectedAmount:
          type: number
          format: double
        currency:
          type: string
        imageUrl:
          type: string
        image:
          $ref: '#/components/schemas/FileUploadResponse'
        projectStartDate:
          type: string
          format: date-time
        projectEndDate:
          type: string
          format: date-time
        numberOfBackers:
          type: integer
        description:
          type: string
        longDescription:
          type: string
        projectVideoUrl:
          type: string
        projectVideo:
            $ref: '#/components/schemas/FileUploadResponse'
        risk:
          type: integer
        expectedProfit:
          type: number
          format: double
        minimumInvestment:
          type: number
          format: double
        rewards:
          type: array
          items:
            $ref: '#/components/schemas/ProjectReward'

    PaginatedProjectsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CrowdfundingProject'
        hasMore:
          type: boolean
          description: Indicates if there are more results to retrieve

    SubmitCrowdfundingProjectCommand:
      type: object
      properties:
        projectStartDate:
          type: string
          format: date-time
        projectEndDate:
          type: string
          format: date-time
        projectVideoUrl:
          type: string
        title:
          type: string
        currency:
          type: string
        requestedAmount:
          type: number
          format: double
        description:
          type: string
        longDescription:
          type: string
        imageUrl:
          type: string
        rewards:
          type: array
          items:
            $ref: '#/components/schemas/ProjectReward'

    EditCrowdfundingProjectCommand:
      type: object
      properties:
        projectStartDate:
          type: string
          format: date-time
        projectEndDate:
          type: string
          format: date-time
        projectVideoUrl:
          type: string
        title:
          type: string
        currency:
          type: string
        requestedAmount:
          type: number
          format: double
        description:
          type: string
        longDescription:
          type: string
        imageUrl:
          type: string
        rewards:
          type: array
          items:
            $ref: '#/components/schemas/ProjectReward'

    ProjectOwner:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        id:
          type: string

    ProjectReward:
      type: object
      properties:
        description:
          type: string
        imageUrl:
          type: string
        image:
          $ref: '#/components/schemas/FileUploadResponse'
        name:
          type: string

    ProjectCreated:
      type: object
      properties:
        id:
          type: string
    FileUploadResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the uploaded file
        path:
          type: string
          description: Path of the uploaded file
        location:
          type: string
          description: Location of the uploaded file
        contentType:
          type: string
          description: Content type of the uploaded file
        url:
          type: string
          format: uri
          description: Public URL of the uploaded file
