openapi: 3.0.3
info:
  title: NextCrowd API
  description: Public APIs available on NextCrowd website
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /public/projects/{projectId}:
    get:
      summary: Get Project by ID
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
          description: ID of the project
      responses:
        '200':
          description: Project retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrowdfundingProject'
        '404':
          description: Project not found

  /public/projects/published:
    get:
      summary: Get Published Projects
      parameters:
        - in: query
          name: cursor
          schema:
            type: string
          description: Cursor for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items to return
      responses:
        '200':
          description: List of published projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProjectsResponse'

components:
  schemas:
    CrowdfundingProject:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        status:
          type: string
        owner:
          $ref: '#/components/schemas/ProjectOwner'
        rewards:
          type: array
          items:
            $ref: '#/components/schemas/ProjectReward'
        requestedAmount:
          type: number
          format: double
        collectedAmount:
          type: number
          format: double
        currency:
          type: string
        imageUrl:
          type: string
        projectStartDate:
          type: string
          format: date-time
        projectEndDate:
          type: string
          format: date-time
        numberOfBackers:
          type: integer
        description:
          type: string
        longDescription:
          type: string
        projectVideoUrl:
          type: string
        risk:
          type: integer
        expectedProfit:
          type: number
          format: double
        minimumInvestment:
          type: number
          format: double
        bakers_count:
          type: number
          format: integer

    PaginatedProjectsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CrowdfundingProject'
        hasMore:
          type: boolean
          description: Indicates if there are more results to retrieve

    ProjectOwner:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        id:
          type: string

    ProjectReward:
      type: object
      properties:
        description:
          type: string
        imageUrl:
          type: string
        name:
          type: string

    ProjectId:
      type: object
      properties:
        id:
          type: string