version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - .env

  database:
    extends:
      file: postgres.yml
      service: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: